#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Debugging Tools
  hosts: Ubuntu
  become: True
  tasks:
      - pip: name=httpie

- name: Pull Down Docker Containers
# hosts: Ubuntu
  hosts: nobody
  become: False
  tags:
  - images
  vars:
       rest_services_tag: 1.0.944.MILESTONE
       core_services_tag: 1.0.768.MILESTONE
       tlo_tag: 1.11.21
       lds_tag: 1.0.898
       mli_tag: 14-master
       journaler_tag: 16-master
  tasks:
      - docker_image:
            name: "registry.transparent.com/mold-e-rest-services"
            tag: "{{ rest_services_tag }}"
      - docker_image:
            name: "registry.transparent.com/mold-e-reporting-event-processor"
            tag: "{{ core_services_tag }}"
      - docker_image:
            name: "registry.transparent.com/tlo"
            tag: "{{ tlo_tag }}"
      - docker_image:
            name: "registry.transparent.com/lds"
            tag: "{{ lds_tag }}"
      - docker_image:
            name: "registry.transparent.com/lds-varnish"
            tag: "{{ lds_tag }}"
      - docker_image:
            name: "registry.transparent.com/lds-nginx"
            tag: "{{ lds_tag }}"
      - docker_image:
            name: "registry.transparent.com/molde-mli-forever"
            tag: "{{ mli_tag }}"
      - docker_image:
            name: "registry.transparent.com/molde-journal"
            tag: "{{ journaler_tag }}"

