#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - name: create groups based on distribution
      group_by: key={{ ansible_distribution }}

- name: Install Debugging Tools
  hosts: Ubuntu
  become: True
  tasks:
      - hostname: name=bravo
      - pip: name=httpie

- name: Start Docker Containers
  hosts: Ubuntu
  become: False
  vars:
       alpha_ip: "10.10.10.10"
       bravo_ip: "10.10.10.20"
       report_generator_http_port: "2080"
       report_generator_jmx_port: "2020"
       report_generator_image_tag: "1.0.944.MILESTONE"

       report_event_processor_image_tag: "1.0.768.MILESTONE"
       report_event_processor_http_port: "3080"
       report_event_processor_jmx_port: "3020"

       mli_forever_port: "4080"

       mli_event_processor_image_tag: "14-master"
       mli_event_processor_http_port: "4080"

  tasks:
      - name: Mold-E REST Services
        docker_container:
            detach: True
            env:
                SPRING_PROFILES_ACTIVE: "default"
                LFS_DOMAIN_NAME: "dumb"
                JVM_HEAP_MIN: "256m"
                JVM_HEAP_MAX: "256m"
                JVM_JMX_HOST: "{{ bravo_ip }}"
                JVM_JMX_PORT: "{{ report_generator_jmx_port }}"
                JVM_JMX_RMI_PORT: "{{ report_generator_jmx_port }}"
                mold-e_keyStorePath: "/tls/keystore.jks"
                mold-e_keyStorePassword: "CHANGEME"
                mold-e_keyStoreAlias: "server"
                mold-e_mliForeverPort: "{{ mli_forever_port }}"
            etc_hosts:
                mongo: "{{ alpha_ip }}"
                mli-forever: "{{ bravo_ip }}"
            hostname: "report-generator"
            image: "registry.transparent.com/mold-e-rest-services:{{ report_generator_image_tag }}"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            name: "report-generator"
            network_mode: "bridge"
            published_ports:
            - "{{ report_generator_http_port }}:8080"
            - "{{ report_generator_jmx_port }}:2020"
            pull: False
            restart_policy: "always"
            state: "started"
            trust_image_content: True
            volumes:
            - "/tmp:/tls:ro"

      - name: Mold-E Event Processor
        docker_container:
            detach: True
            env:
                SPRING_PROFILES_ACTIVE: "default"
                LFS_DOMAIN_NAME: "dumb"
                JVM_HEAP_MIN: "256m"
                JVM_HEAP_MAX: "256m"
                JVM_JMX_HOST: "{{ bravo_ip }}"
                JVM_JMX_PORT: "{{ report_event_processor_jmx_port }}"
                JVM_JMX_RMI_PORT: "{{ report_event_processor_jmx_port }}"
            etc_hosts:
                mongodb: "{{ alpha_ip }}"
                rabbitmq: "{{ alpha_ip }}"
            hostname: "event-processor"
            image: "registry.transparent.com/mold-e-reporting-event-processor:{{ report_event_processor_image_tag }}"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            name: "event-processor"
            network_mode: "bridge"
            published_ports:
            - "{{ report_event_processor_http_port }}:8080"
            - "{{ report_event_processor_jmx_port }}:2020"
            pull: False
            restart_policy: "always"
            state: "started"
            trust_image_content: True

      - name: MLI Event Processor
        docker_container:
            command: [python, manage.py, consume]
            detach: True
            env:
                MLI4EVR_AMQP_HOST: "{{ alpha_ip }}"
                MLI4EVR_AMQP_USER: "guest"
                MLI4EVR_AMQP_PASSWORD: "guest"
                MLI4EVR_AMQP_VHOST: "/"
                MLI4EVR_AMQP_EXCHANGE: "exchange-events"
                MLI4EVR_AMQP_QUEUE: "mli-forever"
                MLI4EVR_AMQP_CONSUMERS: 10
                MLI4EVR_DB_HOST: "{{ alpha_ip }}"
                MLI4EVR_DB_USER: "root"
                MLI4EVR_DB_PASSWORD: ""
                MLI4EVR_DB_NAME: "mli4ever"
                MLI4EVR_DEBUGGING_ENABLED: "True"
                MLI4EVR_LOGGING_LOGFACES_HOST: "192.168.254.123"
                MLI4EVR_LOGGING_LOGFACES_DOMAIN: "mli-tlo-sa"
            etc_hosts:
                mongodb: "{{ alpha_ip }}"
                rabbitmq: "{{ alpha_ip }}"
            hostname: "mli-event-processor"
            image: "registry.transparent.com/molde-mli-forever:{{ mli_event_processor_image_tag }}"
            log_driver: "json-file"
            log_options:
                max-size: "50m"
            name: "mli-event-processor"
            network_mode: "bridge"
            published_ports:
            - "{{ mli_event_processor_http_port }}:8080"
            pull: False
            restart_policy: "always"
            state: "started"
            trust_image_content: True

